Repository andrej-hajduk/XRF-13, pull requests merged in 2021-07, with the labels that each got.

#42 Tries to tone down excessive sanitation
  code/modules/client/preferences.dm
  code/modules/economy/cash.dm
Labels: Fix

#40 Survivor Overhaul
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/preferences.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/hunt.dm
  code/datums/jobs/job/survivor.dm
  code/datums/jobs/job/xenomorph.dm
  code/datums/skills.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/reagents/reagents/medical.dm
  icons/mob/back.dmi
  icons/obj/items/storage/storage.dmi
Labels: Balance, Refactor, Tweak

#41 Expands Random Crate Loot
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Balance, Tweak

#44 Adds a 'subtle post' variant of Psychic Whisper
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Labels: Feature, Port, Xenomorphs
