Repository andrej-hajduk/XRF-13, pull requests merged in 2021-06, with the labels that each got.

#1 Xenomorph Flavour Text
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/xenomorph/login.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/BackgroundInformation.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.tsx
Labels: Feature, User Interface, Xenomorphs

#2 Fixes being able to overload message sanitisation
  code/datums/jobs/squads.dm
  code/game/verbs/ooc.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/pray.dm
  code/modules/mob/camera/imaginary_friend.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
Labels: Fix

#3 Vote Config Settings
  config/example/config.txt
Labels: Configuration Change

#4 A few feature ports from TFO:A
  code/__DEFINES/__game.dm
  code/__DEFINES/admin.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
  sound/ambience/votestart.ogg
Labels: Feature, Port, Tweak, Xenomorphs

#5 Adds server-side updates to the repo
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Tweak

#8 Permissions, Recipes, and Shipmaps
  code/modules/admin/debug_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/server_verbs.dm
  code/modules/reagents/reactions/medical.dm
  config/example/shipmaps.txt
Labels: Administration, Tweak

#10 Grenades removed from common marine vendors
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance, Marines

#9 [NONMODULAR]What da king doin?
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Balance, Xenomorphs

#14 Fixes issue #12
  code/game/objects/items/storage/fancy.dm
Labels: Fix

#16 [NONMODULAR]This was a bad idea
  code/modules/reagents/reagents/toxin.dm
Labels: Balance, Fix

#11 fixes access on research doors (Sulaco)
  code/game/objects/machinery/doors/airlock_types.dm
Labels: Fix, Map Edit

#15 Psychic whisper while resting
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Tweak, Xenomorphs

#22 Stopgap - Removal of acid turrets + dead bodies on maps
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/modularmaps/lv624/internal_affairs.dmm
  _maps/modularmaps/prison/civresgym.dmm
Labels: Map Edit, Tweak

#20 Panic Bunker Whitelist [TM Needed]
  code/__HELPERS/admin.dm
  code/__HELPERS/time.dm
  code/_globalvars/lists/mobs.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/persistence.dm
  code/modules/admin/holder.dm
  code/modules/admin/server_verbs.dm
  code/modules/admin/verbs/chat_commands.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client_procs.dm
  code/modules/events/_events.dm
  config/example/config.txt
  modular_skyrat/code/controllers/configuration/entries/skyrat_config.dm
  tgmc.dme
Labels: Administration, Configuration Change, Port, Test Merge Candidate

#25 Map votes at the end of the round
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/datums/gamemodes/game_mode.dm
  config/example/config.txt
Labels: Configuration Change, Tweak

#18 Xenojelturret&larvajelly
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/reagents/reagents/food.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/Xeno/jelturret.dmi
Labels: Code Bounty, Feature, Xenomorphs

#28 Removes king evolution
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
Labels: Revert/Feature Removal, Xenomorphs
